language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0

# These implementations are failing as of writing  
#  - rbx-19mode # Has an encoding issue.
#  - ruby-head  # Has a YAML parser issue.

# Haven't looked into these issues as yet
